---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jewellery-catalogue-api-secret-prod
  namespace: jewellery-catalogue-production
spec:
  encryptedData:
    AUTH_URL: PLACEHOLDER
    CONNECTION_URI: PLACEHOLDER
    DATABASE_NAME: PLACEHOLDER
    PORT: PLACEHOLDER
    MINIO_ENDPOINT: PLACEHOLDER
    MINIO_ACCESS_KEY: PLACEHOLDER
    MINIO_SECRET_KEY: PLACEHOLDER
  template:
    metadata:
      creationTimestamp: null
      name: jewellery-catalogue-api-secret-prod
      namespace: jewellery-catalogue-production


