apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shoppingo-production
resources:
  - base.yaml
  - api-sealedsecret.yaml
  - mongodb-sealedsecret.yaml
patchesStrategicMerge:
  - patch-deployment.yaml
  - patch-ingress.yaml
replacements:
  - source:
      kind: SealedSecret
      name: api-secret-prod
    targets:
      - select:
          kind: SealedSecret
          name: api-secret
        fieldPaths:
          - metadata.name
  - source:
      kind: SealedSecret
      name: mongodb-secret-prod
    targets:
      - select:
          kind: SealedSecret
          name: mongodb-secret
        fieldPaths:
          - metadata.name