apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shoppingo-production
resources:
  - ../../base
  - api-sealedsecret.yaml
  - mongodb-sealedsecret.yaml
  - patch-namespace.yaml
patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
  - path: delete-namespace.yaml
  - path: patch-pvc.yaml
  - path: delete-api-sealedsecret.yaml
    target:
      kind: SealedSecret
      name: api-secret
  - path: delete-mongodb-sealedsecret.yaml
    target:
      kind: SealedSecret
      name: mongodb-secret
  - path: frontend-configmap.yaml
    target:
      kind: ConfigMap
      name: frontend-config