apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shoppingo-production
resources:
  - ../../base/namespace.yaml
  - ../../base/mongodb-deployment.yaml
  - ../../base/mongodb-service.yaml
  - ../../base/mongodb-pvc.yaml
  - ../../base/deployment.yaml
  - ../../base/service.yaml
  - ../../base/web-deployment.yaml
  - ../../base/web-service.yaml
  - ../../base/configmaps.yaml
  - ../../base/ingress.yaml
  - api-sealedsecret.yaml
  - mongodb-sealedsecret.yaml
patchesStrategicMerge:
  - patch-deployment.yaml
  - patch-ingress.yaml