apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shoppingo-production
resources:
  - base.yaml
  - api-sealedsecret.yaml
  - mongodb-sealedsecret.yaml
  - web-sealedsecret.yaml
patchesStrategicMerge:
  - patch-deployment.yaml