apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shoppingo-production
resources:
  - ../../base
  - api-sealedsecret.yaml
  - mongodb-sealedsecret.yaml
patchesStrategicMerge:
  - patch-deployment.yaml
  - patch-ingress.yaml