apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret-prod
  namespace: shoppingo-production
spec:
  encryptedData:
    password: AgBoBIJwf6h62poXdEOoM1oX29VAAEz5d8D1MdNxY+dbz0h/ACmmOIqy01ixkrMbBjF6KuWvGGxxpYpZXR5C0/Mk6eYDwHn+DFFxmu+NxoSB16wOOkEug9OLIqrTEY6HxPKFsJoQWWTkFwfdfqGlQL8FO4Acb2tAvyB+yhBnbfD4JfwhyQKOk0keXqflZks78pSdhdS9XVA8A0V5h2UV3F4EgFR4Ws4uNslI0rmii2eKaD3Nt4JsPlI82dXpj9BVGnk/DxGTZniUwW8ZmwNabT2ErYJS/hQAlTI9vDCNaVk8O2xCs+XGxYhVMbaosQDYrV+rP1bwDDS1JdtUXtY3pikzx97VWd99uXG51ekqLIPkN8UepOIg25ikmlrXLEdE46XJQ9GPEASh0/hEw3rregHgI0Cu0rBNVOVYKatxQv4TbR9TACrB5MkwQX72pBprOjK9/JQcUHuSeDqicy6kTAn7SzWQIpC0WOBAUUGbn+VlSDW29yCnhsE0ixULXx6yvjt0MCvk+BJVo4Cmo5MoRW+AEYDhzDfai2Kxi+mdKGm47hdC62YFhCHEJRT4Ik+FmRGEitvpWk+vGn0+gs6Ejqasz/WjckwDu119S7433hATdeMCRF3b1YbC93qb2Om7HUqBbf2G41GzS1BEcLHDLh6BHQEX03XX8CRJyH1Fi+P3KxCnGAdcMxcb/nhb5GxWSujHON2TBRA9oCIstT59aRSSz/zL86U=
    username: AgBRESVu9SKGUu8Mw6JZPmqDksX25EDSUj2EQftY/OERHH79pPTzhyn2GQRSHU+M6PZwHI8ks5Fjly33JSLb0v9yHLKYKgA9nEHXhkT2dgOSgLjdoV8gDyVRJm/nypHgC8FTtnKqg7zgxKSyQ79NBNm6+kWZi4IKhW+H/9vsA0GTBHbPe4z6IhYarhBdrYPsT1l5qOyyKM68j5KSwNL9flFUl8SZfuiNXFvP35Y2TEVsCgZX8Viq7TKAAGXDRvYE6MW4O5UIUd2mBBPgtoE2HrsxxO5t3iljchfL5kfMCXDtL0HpNq9nLCB43lobZDE4bScsOgC0pzm/HBh8fGVuMNMnnmTlSSPR76QhnUOXm9Ti9x2dgZOb6toCmWUo+PXNibsxuX4TGnK794XrZoW8Pn88X/ztgzPVr9dbeKN+jINFpoGPdePBHotir5bwMCSfmrnzaWxx4I0IRuDjr4XaMWzXqoX8aY3PH+Q9wOfGH9ir7YukRzATYl66fVHK63sjTDnF9ErktmFFA/Shr2f8QYisusuBPxejr8oPP/sV0dFjSCYwzl0ysID4aJeikFIJuRzMZzgGSqJ70nZs4LpYYPxahWyLWbnIvKZhX2Piohnw7GM1+tsPAeapaoF0rogsXf4YMp5vHLR89e6pjfGLLwOZCoOfWRCJu/4GVFVzlBAhNzQlT9uk/7SeDSpQtXanxIR/5ul9LXZw9B9xHaHQGD4EqzC5Sg==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret-prod
      namespace: shoppingo-production
    type: Opaque
---
