---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret-prod
  namespace: shoppingo-production
spec:
  encryptedData:
    password: AgA0tgCJBSuSCSybNiA5qMHlevQ/NyYyIpBpGgOTcn6/Gr2wOR+reXEbHGJQ1FK0ltNwI8Bct7a1lkKENulq/u1PeHrNsO/vHyaiC5NrCxf8c1SR3pVnwqSGE8MWHn+WILKzQCmDgwa0W1pRlKvUJ+BH7WzPQT9V/EYxq1yU8P/a9mchtSwfuWqhSTj28iIWU0MFIjdGoZoHhBKd3IJpzgH5N1fl70bASZgGPDLMt0o6ZGW2nYwGptBq+rU+vcp5lCvZhfjBAByTZ0DlNiN9REHovgMd+8OlCi4zuJBhDppa2G1akKGnh8iXHs7i2DiSrBTApqpa5s3yF27D1diDnya2lWFUNC5a2mgw3veDs/Ki66X7XEOqdKodVI0H5t6KjEXabxR+yZ5rD1eujghESeD2UErqEwE8BG7mVIHCFxe/FUEidZS+KNZdpdbLLT+FB2cwWEEcf6KzjSYALFa2sI0vfcXqR5d0/0ZwP6DQhxCBY/C4t6vy+1U5hEgwRyQC33Y/YFJ8tU1tYFdeYXSLRYO61v3dgroG27yndqxyFYWKENBRv9b6told1ob7al1FUnRrbJWsKx3Av28pVn6OQrmdyGEjl1BMcJtbLx3u5MZK2qBSpTWwmdLYqXWUBgPteBNoFxcJc0f+1l2D7P6UDK5UJC0GiGaucMJNqKKPDo6UT6+n6SbyWZnnhiztESKWmiEEEPE5SX+8WGqIWPpYMMGqlQH1pA4=
    username: AgBNzS/NQSzIDIA7oILVogNUHYaR9/5irwHwE9n/ocIlP+IWMmlsP04KL4JRsNdCNEr68MD6H2TDtp2V9ds2u37AZCH8bNtfTUGH1IZMUq6sX+cE04fpeqxuONdrV4oyJvw4Lcgj90y+QIKt4GcZfRVmQ6oEL8VsMAtui/eaXtGQ+dnalIkVHrBrIX9JKJqQ9gpCom2r5rbHAcZYa+UadsDuKOzqTfO5lZyem/plz3Ke2YTmm/FEqOtmWwoerAYh9CSpvwdK3Jwbuv4BJQPPq3PqCZwIwKO5n9itbP7//g4yPs4TLdPrahFUi+rXMs2/iq6e5ffLcYZIgvj1qUaQLbyRSBvtu10lD1AYj13xWwihrnyZk2zftE1QzxVmzCncta3o8m4FRsgOQnlr9pLMeoXCUkNeO0bfh2/05ZLgWUgQxQY8EGam5lG8ICG7DJvyc8JUklX3bk7W3L0Lx41JEjFCu+vK6EPKNg0Omdl8MNua8abmRqbyJLqUlv12cMpakGchIc4ht5s6NqjUTCywQjyDf6w9vnoR613/xF7EB2USAe/tXoXAbXXJDSuXDT6Tu38xQpkwq/L5XX+7slnx0O0INvE03HYuYh5CN09kcWRk2ELmnwv4/EfiChG49hX9aUT3ajV9DNyl4n3QPtab1pjiQujw3ctTA+GuK+1R0wHHbhGyI9qTZ+U9ZHBqZM3kQ/huUOMF2gqfDpeB6JzkbLVNRNhOBw==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret-prod
      namespace: shoppingo-production
