apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingo
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: shoppingo
          image: ghcr.io/igor-siergiej/shoppingo:prod