apiVersion: apps/v1
kind: Deployment
metadata:
  name: kivo
  labels:
    app: kivo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kivo
  template:
    metadata:
      labels:
        app: kivo
    spec:
      containers:
        - name: kivo
          image: 192.168.68.54:31834/kivo:placeholder
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: kivo-config
          env:
            - name: PORT
              value: "3000"
            - name: CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: kivo-secret
                  key: CONNECTION_URI
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: kivo-secret
                  key: DATABASE_NAME
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kivo-secret
                  key: JWT_SECRET
            - name: ACCESS_TOKEN_EXPIRY
              valueFrom:
                secretKeyRef:
                  name: kivo-secret
                  key: ACCESS_TOKEN_EXPIRY
            - name: REFRESH_TOKEN_EXPIRY
              valueFrom:
                secretKeyRef:
                  name: kivo-secret
                  key: REFRESH_TOKEN_EXPIRY
            - name: SECURE
              valueFrom:
                secretKeyRef:
                  name: kivo-secret
                  key: SECURE
            - name: SAME_SITE
              valueFrom:
                secretKeyRef:
                  name: kivo-secret
                  key: SAME_SITE