apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmaps.yaml
  - kivo-sealedsecret.yaml
  - mongodb-deployment.yaml
  - mongodb-service.yaml
  - mongodb-pvc.yaml
  - kivo-mongodb-sealedsecret.yaml
