apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: shoppingo-staging
spec:
  encryptedData:
    password: AgCgM5qykcdKYEDyEA8bVW3VtFAO/9Kf3gO7P2Cjx4aTUgVk1OF93L1p6QajsSXwcp4L9CMy5F1xfVDLTGyoLtYN0kGGqslGNJTVM2H99R1xpbY9UvtEcXwEcIs0a88tYj7u58susr5c+7sqrxZMiIyAtC2RiusFsrpeEr1I9w7afD4L586mvZKLuWWJFvKTxWku/cahgPKi1d/NxhlXgullXYuD+tn0S578aN4CFYkh+Hg8ivltYOIxh5V78MSnS2z3PCwkWDeJE84+Ky94em+h6Z7LwNodgvgRw7ZUgmpg+8R+UQzZpL07plSpSMRBnAsy11KMrEBACP41w3IZWW2xtK0AiZ3M98NZj9DhUXxft5RKDqfgPElR7HQuwyYESDbJVkNQj2lcPuZePN9xOfXcDR3N1i/E28iN8dGK16BH1r4r6Um1SGuxqlxmyjken/hVHxxNm1uWJMA2cqIafJHrERqQBN53dfiqb+efg1jABPlpDyxyFljhW4+cg/MCHwbp9DKch5Z0ipZc2ngKORpgM2A+pHUcE39/fesUm04gTQ+qaM3q8Yug9VKGrBLGxPNX50pJxc7mluOY+1DiWs2iN87GGZQpZKpHJDDLfoTH9dvqOzLA16b8yb+a3VLOafqcxO3N0oG9fN7wIO9hSuf6MYwu4KCKeJFvrdXPdSzWrbzoOUoXGSLU9B0nKd+Ojj7gqLqyx6z6g8p0MlN4ngfpCI2n
    username: AgC/w75EVkZrAHEdX9ZGImIxue/HnG5D72pZRgygRsoP/rluCh2h1CU+2qTMma/oKmF3lzZQxjVfyVPcHmwGyuY2urWX08pL0Tqrv/t5qSsc/P26ig7P9xjOtObwNIlTdQmJVnw7aKdh0KXp5Bww3QjVKzBqyfldXmkftxHyeBy+I6WtLplg8Uv+D7ayPWG52cpaAUpm2iZEm7H+fODyp0bmbVvj4RTAK+jtc8KTpmDjZp9I5/gSmsUW60sqvYeq/n+mDBTGBVEs7HLcSVHoTUfZtO+HL5NC4bIF2A5Gy5nByNd6Pe92azytfsEko6ucP6pPOcitfNRE2QTw90lvqHj7zoqNSD1Rl96HL9I1JmBNRo2LBa4we4ys44IYAAH1i63gW+uNB/2VO9n042h07mP8XUGSxjtUUc7kumZo/67xaQtkWhjFPzt+js9JW21FuH9e93I2MN2sF6vJq3TKje5tE03YBVBQfTxkaFO6mGkh/MbAfi1qlhEdDo/+YsFYaNlTiBUNAhpe7Z8qUrJjs56K1ZWBhcbCbcIr++0AUxfncCXJzoVnjvDgQBeaUC+Wbf9Dj67YEyUFDQS6INSHDeG4fAXI4NNOV+nJWEpfiFAHFN6+oGuq2gJU309gtPjtVJVFLYIHYe6N+6Oc3HNiBhNycWb6ZSOuufrmPJzZjz2OiXj6yoptPl4P+pUFGnyFVS+P23u3hP3GFvCmAtO8xg==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: shoppingo-staging
    type: Opaque
---
