---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: default
spec:
  encryptedData:
    password: AgCsAXdvOr/j5CB/KXR/0xQErjKjxcicszPemr9vDip3kdrzPhoN1jXQ/KyP/1Zktldb92k422ov+yzApPCZsVIpByxjrJZu3j5lRK+LuhBsWGRFz/SHuFV3Ffn/n1y1BbzSn7KgwMaVyN4dPvHIdYTphlQ8LpNgD/t5YujbolUvJ5WRJvGZavu0440vGecbRP2snQxHRR+fTq8bKBzNstEHm24NYj20pCi5s1CJ3CexozaQGPAEVCFuKlijjmL/WpQ4HsDXiOeaTdcMx3UUAER8XZ4Hm5qmnPcxXb+Y/uu7SM1WMGvWODa7ICrErS8IvA6yVxsTFY0F7QDPrZLvMgLrB1T6esQwWiRhuztj9wRg6+NUo6f3BHQVsCrCLUPtYYyAKBWczFgt01HsKlMKz1hQvXEyACcYA7D6k9y66NyXl/v6PE54Fnx94lsG/BkPCeyvqwCkBgRJMJtbOvn4fecr+4sjxTJ4ZgsVyDfvTSSc+CWlwqj5/ODp00RtmarIErRJbXOK7l1s+IVDpbxQzsYARBoBm5nVxtd1hm/KrLZ2/sRn4b2iORptenAJUUZklgSw0vziMfqiXy+dQgMCuWhx69MlIvvKmhw35E9s/4YfQJfCNUJhEeavibPb3K5NTGBh1gdrSprcfR8ulHS1hUQnwh2hWA9zm6+hiCOPJxKoOi08hK6GD0mxkAs2zTdc9MvbgcwZSRqkq1fKMLkBNmJksi3l
    username: AgAseojpjTcrBhMd6Jmg2wtl5MfRbqonvWhhPV/mlIfbQLomZSMeqPweG0YXpDA2ouL9dhkHsbresXd1YQaaCqNlR9IaQ9QeG+FbqWULfw9oWxoCZSwTN+jP4tJHVJQ7wlI1MCTdZ6SQXTaBvNLKPldwe1JUhfNHvtYBwfbR3e2qhLkgva6Lrmddhdyvb8vl8bBsVSzau36uzYzXIEPDJmRUWu3jG6G1N6s687I9lnRN9AE+KW15aOxCySmTXM4H1vc2Kl4k4cI6ECWG71VsW5LmYu8HdBNjZSgL/gZ8/ZYZfV7FKZGNufnojYfjlDDQHy353RO8Wbn8J7I1RbvRKYPATHdalf2oqPPP/b+ELvwLvEUv98nfsNoiwVeiqe5j6SJyNrvI+5BotVbp3h3vJnfYRSUWl4X72+upkUcAkytB1xAWEtwmPAUsJ6NZ+xs9MEa79NtyKPc4yUrK0RCx/utgF/9MjqLTAsVl5ld6YYcJnzHSbderOwWNv+yUeEXuX8JVnrV9WdD7bvhsUfttpZ9qxxGDA00eZckNvYF1NBw5qNyol5udD3YkYieDjU3mkO/s/oqncc9vyw5aiYJ89s8hXmUYm36YWGdB1k4UsEPPKgMeo5Jd8LS7tj/lb+SmtEEepgyX0hYd7+cqNAx9VqZFGHX/QZJRUYdbWbJXepbfAxcDqR5NQAsXUhNOPVS15Q3gn27Qs8ElIYPwAkr/gQ==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: default
