---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kivo-mongodb-secret-production
  namespace: kivo-production
spec:
  encryptedData:
    password: AgAZCEeTodhB6EMdBtmGmN4BmRORMCKtSsPHDurNN3KpLC4/YNtD1PiCPGBQUa9X39pdLEHcPwgE5P9M60Lg+AzKheqQGM/teUCHCFnzfTZYhjNGK7TAF5j4ltivgM3wVLy2B1VHXuBYDrbP8aVMHGs2oAJznzH7YxnoVfI9JAfUOpFoM0P7d2ZUldEV626xxVK0z+cwXERdQ1oTyNSM0HTMwvY3j12ag+FXx+O2yv5GWLtMDv6uCiNlk/zLRZowyLDICiKgbjILkk4q92lJrh2qCuzOO6aLqXSMZhp1iLVin6gBD6rd7jw+lSqH3X54aew4PoHL3XIM9ezOa/TDOFkQU5JMfqL0CqDhbEAI1lHIgP04ZLSKZmbGIQ+X+HhIwYKCIjMXlSUqlujvGRBHXAyCvDYw69vtHDRDqhsF20/ZPgMOJVYSLwozDEik3Ik5kZdSWzCWuAMbuHk6iO58ctHW02C0FkXe++740GaXy/BPXLHHksRQGaTR0iBnHZS5z+hHGt2L8hIAuXIimsDfI3q44bNuIgn5rxQvZWHpr1+YNXZA70PpbcK5trw7+gZrEUWI5jZuAwP2wEsFcsdkxz1aJaoBkmXlKzeIMcj5darNpxYV9ZpG7KkfWnPW2HGCnipaf4ReuNYWuKhmucF5cQSkzXSdrpthKWDwhEg5RKS4Nvbxq36Bgx0/JwrsqVPhj5IRvxKGmNMd5hrxgR4x27bnILrE7Irkn2IZoxI1EMRj3vMQuCCqIpkr
    username: AgAmHeG3hg0OGe6fU4YoSnjQjW5ikSgHryDoSFYEibomHmmgqMs08i7rsrWbxXl9yOZZ36+9CTVu+hKIvW7lkLxGZQ/bvEDM1QVkJMU8QmmXp/0Tg9Uc316vSXHUQep5WCsfC3pUUf9xYqQHEBSz5h/GdBTYysthW6xDpqbkG+GC2wVfsjWyxjuy6Q63X0T47Il0riH+fp5dHLrBnVwZ2g+q4lrFDFPgni3PnqE+8MS/PmyxQB9UbwvceMKBwuXFzy2vgND/ZMHxWwXTQOm3HjCSqm/rEGgiVHbw6kzp97wF1OHgvQ25cHHDjq3ZKxbGp4AM1k01U4//kBBHVeZYG8KyV5sW78/hmaWKcxHl0v7ExVB1VYE1484fCFUJcKGgcvwXkrbWqp+kFP3xfTaFQwncup3pcBkCumFJqAkyTQLH13Vm+Sk/UXSK4hyg2kSBmQjELLUZjJgghqGIeNmGX42Hv/SvtTBFWkOpzpVJb14/NIQV3IghKk8BGyg0uxDWPnObobY/97APhrmHlEfwzN0LluTFFKvDg/pypx/HiSY+9aLsV5N5TBfYflBgTLT74BvGHQfMKs0wPPlP112CYBxwnXDxPeF+g6RfM0ITzOnOrDwT9UITLNHmmGcBBVP9uu7DJ7+d2qj4oqgiiV9Lqu9EDFUpKoGGoJqtOBfIpYiUTGecrpujCYSoWI1lfDFiBbfjwPtbvrAXqZJ+8zlw8F4=
  template:
    metadata:
      creationTimestamp: null
      name: kivo-mongodb-secret-production
      namespace: kivo-production
