apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kivo-production
resources:
  - base.yaml
  - kivo-sealedsecret.yaml
  - kivo-mongodb-sealedsecret.yaml
patchesStrategicMerge:
  - patch-deployment.yaml
